site_name: Téc. Sub. em Redes de Computadores
site_description: Técnico Subsequente em Redes de Computadores

theme:
  name: material
  language: pt
  palette:
    primary: green

plugins:
  - mermaid2
